version: 0.0 # CodeDeploy 버전
# 프로젝트 버전이 아니므로 0.0외에 다른 버전은 오류
os: linux
files:
  - source:  / # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상 지정
    # 루트경로(/)를 지정하면 전체 파일을 이야기 합니다.
    destination: /home/ec2-user/app/step3/zip/ # source에서 지정된 파일을 받을 위치
    # 이후 Jar를 실행하는 등은 destination 에서 옮긴 파일들로 진행
    overwrite: yes # 기존에 파일들이 있으면 덮어쓸지 결정
    # 현재 yes라고 했으니 파일 덮어씀

permissions: # codedeploy에서 ec2 서버로 넘겨준 파일들을 모두 ec2-user 권한ㅇ르 갖도록 함
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user